### ISSUE TITLE
boilerplate code anlegen

### ISSUE THREAD

**Issue by erganmedia** [ob-algdatii-ss18/leistungsnachweis-a-team-1#2]

**Comment by NikitaHans** [comment]
Is this done? There was no review and its merged into master already.
I will set up some Workflow steps to ensure this won't become the normal flow.

**Comment by NikitaHans** [comment]
@erganmedia Please Review this ticket so we see if its actually correct inside the master.
Not completely issue solving commits should be kept in a dedicated branch unless they absolutely need to be merged into master.

**Comment by NikitaHans** [comment]
Issue closed, has been resolved by @PMmuc directly on master.
