### ISSUE TITLE
Create Datastructure for labyrinth

### ISSUE THREAD

**Issue by NikitaHans** [ob-algdatii-ss18/leistungsnachweis-a-team-1#4]
### **o** Datastructure as an Array of Integers with values 0 and 1
 - 0 representing free
 - 1 representing blocked
### **o** Create static Class to handle such operations 
 - Reasoning being that we should capsule such pure logic functions in a dedicated class

This is the first issue I created so please give feedback and help if there are things missing or things you don't agree with.

**Comment by janneskretschmer** [comment]
Ich würde lieber eine Klasse Maze implementieren, weil wir beispielsweise Start-und Endpunkt brauchen. Außerdem wäre der Zustand "visited" von Vorteil für die Visualisierung. Intern würde ich auch ein zweidimensionales Array verwenden aber eher mit einem Enum als magic numbers. Die Getter für Start-und Endpunkt können ja ein struct mit x-und y-Koordinate oder so zurückgeben.
Die Logik kann trotzdem in eine Service oder Util-Klasse ausgelagert werden. Ich kenn mich zwar nicht aus mit CPP, hab aber [hier](https://stackoverflow.com/questions/8226489/organising-utility-functions-in-c) gelesen, dass man statt Klassen mit lauter statischen Methoden lieber einen Namespace definieren soll.

Die andere Möglichkeit wäre einfach ein Array mit den Enum-Werten FREE, WALL, START, END, VISITED und utility-Methoden oder so ähnlich, das finde ich persönlich aber etwas unsauber.

**Comment by PMmuc** [comment]
Meiner Meinung nach sollten wir eine Graphen-Datenstruktur implementieren, weil:

- das in der Vorlesung vorkommen wird
- der A* Algorithmus auf einen Graphen angewendet wird. https://de.wikipedia.org/wiki/A*-Algorithmus
- der Ansatz allgemeiner ist

(Dafür sollten wir dann vielleicht kein Array verwenden bzw. eine Matrix, sondern eine Adjazenzliste.. -> weniger Speicherverbrauch. http://www.tilman.de/uni/ws03/alp/adjazenz.php.)
Ich würd das auch machen, wenn keiner was dagegen hat :)

**Comment by janneskretschmer** [comment]
Gut, mir solls recht sein ;)

**Comment by PMmuc** [comment]
Die Grundlegende Datenstruktur wurde erstellt. Erweiterungen werden in extra issues geschrieben.
